# Site settings
title: Speech to emotion recognition demo
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:
# Team names, titles and social links
people:
- name: MIPT
  pic: mipt
  position: Lead Designer
  social:
    - title: github
      url: #

- name: Alex Seikin 1
  pic: seikin
  position: Lead Designer
  social:
    - title: github
      url: #

- name: Alex Seikin 2
  pic: seikin
  position: Lead Designer
  social:
    - title: github
      url: #

- name: Alex Seikin 3
  pic: seikin
  position: Lead Designer
  social:
    - title: github
      url: #

- name: Alex Seikin 4
  pic: seikin
  position: Lead Designer
  social:
    - title: github
      url: #

- name: Alex Seikin 5
  pic: seikin
  position: Lead Designer
  social:
    - title: github
      url: #





# # Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#   - title: twitter
#     url: http://twitter.com/jekyllrb
#   - title: facebook
#     url:
#   - title: stack-overflow
#     url: http://stackoverflow.com/questions/tagged/jekyll
#   - title: bitbucket 
#     url: http://bitbucket.org/jekyll
#   - title: github
#     url: http://github.com/jekyll

# # Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
